// Package config defines the runtime configuration for ktalk-core.
// A config is typically loaded from a YAML file or decoded from a URI.
package config

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/url"
	"strings"
)

// Mode determines which side of the tunnel this process is.
type Mode string

const (
	// ModeCreator is the server side — sits outside RU and provides egress.
	ModeCreator Mode = "creator"
	// ModeJoiner is the client side — sits inside RU and forwards traffic.
	ModeJoiner Mode = "joiner"
)

// Config is the complete runtime configuration for a single ktalk-core process.
type Config struct {
	// Mode is either "creator" or "joiner".
	Mode Mode `json:"mode" yaml:"mode"`

	// Room describes the Kontour Talk room to join.
	Room RoomConfig `json:"room" yaml:"room"`

	// Crypto holds the shared secret for AEAD-encrypted DataChannel frames.
	Crypto CryptoConfig `json:"crypto" yaml:"crypto"`

	// Net holds network-related tunables.
	Net NetConfig `json:"net" yaml:"net"`

	// SOCKS5 holds settings for the local SOCKS5 listener (Joiner side only).
	SOCKS5 SOCKS5Config `json:"socks5" yaml:"socks5"`

	// Sub is the optional subscription URL for config auto-refresh.
	Sub string `json:"sub,omitempty" yaml:"sub,omitempty"`

	// Debug enables verbose logging.
	Debug bool `json:"debug,omitempty" yaml:"debug,omitempty"`
}

// RoomConfig describes a Kontour Talk room endpoint.
type RoomConfig struct {
	// Subdomain is the subdomain of ktalk.ru to connect to, e.g. "ilte0310".
	Subdomain string `json:"subdomain" yaml:"subdomain"`

	// RoomID is the room path segment, e.g. "abcdef123456".
	RoomID string `json:"room_id" yaml:"room_id"`

	// Hash is the optional #hash appended to the room URL.
	Hash string `json:"hash,omitempty" yaml:"hash,omitempty"`
}

// WSSUrl returns the WebSocket URL for the XMPP connection to this room.
func (r RoomConfig) WSSUrl() string {
	return fmt.Sprintf(
		"wss://%s.ktalk.ru/xmpp-websocket?room=%s",
		r.Subdomain, r.RoomID,
	)
}

// HTTPBase returns the base HTTP URL for this room's Jitsi instance.
func (r RoomConfig) HTTPBase() string {
	return fmt.Sprintf("https://%s.ktalk.ru", r.Subdomain)
}

// JID returns the bare JID of the MUC room.
func (r RoomConfig) JID() string {
	return fmt.Sprintf("%s@muc.meet.jitsi", r.RoomID)
}

// FocusJID returns the Jicofo focus JID.
func (r RoomConfig) FocusJID() string {
	return "focus@auth.meet.jitsi/focus"
}

// CryptoConfig holds the ChaCha20-Poly1305 shared key.
type CryptoConfig struct {
	// Key is a 32-byte key encoded as hex. Generated by ktalk-panel.
	Key string `json:"key" yaml:"key"`
}

// NetConfig holds network tunables.
type NetConfig struct {
	// DNSServer is the upstream DNS resolver used by the tunnel, e.g. "1.1.1.1:53".
	DNSServer string `json:"dns_server,omitempty" yaml:"dns_server,omitempty"`
}

// SOCKS5Config configures the local SOCKS5 proxy on the Joiner side.
type SOCKS5Config struct {
	// ListenAddr is the address to listen on, e.g. "127.0.0.1:1080".
	ListenAddr string `json:"listen_addr,omitempty" yaml:"listen_addr,omitempty"`

	// Username is optional SOCKS5 auth username.
	Username string `json:"username,omitempty" yaml:"username,omitempty"`

	// Password is optional SOCKS5 auth password.
	Password string `json:"password,omitempty" yaml:"password,omitempty"`
}

// Defaults fills in zero-values with sane defaults.
func (c *Config) Defaults() {
	if c.Net.DNSServer == "" {
		c.Net.DNSServer = "1.1.1.1:53"
	}
	if c.SOCKS5.ListenAddr == "" {
		c.SOCKS5.ListenAddr = "127.0.0.1:1080"
	}
}

// Validate returns an error if any required field is missing or invalid.
func (c *Config) Validate() error {
	switch c.Mode {
	case ModeCreator, ModeJoiner:
	default:
		return fmt.Errorf("invalid mode %q: must be creator or joiner", c.Mode)
	}
	if c.Room.Subdomain == "" {
		return fmt.Errorf("room.subdomain is required")
	}
	if c.Room.RoomID == "" {
		return fmt.Errorf("room.room_id is required")
	}
	if len(c.Crypto.Key) != 64 {
		return fmt.Errorf("crypto.key must be 64 hex characters (32 bytes)")
	}
	return nil
}

// EncodeURI serialises the config into a ktalk:// URI for distribution.
// The payload is base64url-encoded JSON — compact enough for a QR code.
func (c *Config) EncodeURI() (string, error) {
	b, err := json.Marshal(c)
	if err != nil {
		return "", fmt.Errorf("marshal config: %w", err)
	}
	encoded := base64.RawURLEncoding.EncodeToString(b)
	return "ktalk://" + encoded, nil
}

// DecodeURI parses a ktalk:// URI back into a Config.
func DecodeURI(uri string) (*Config, error) {
	if !strings.HasPrefix(uri, "ktalk://") {
		return nil, fmt.Errorf("URI must start with ktalk://")
	}
	payload := strings.TrimPrefix(uri, "ktalk://")
	// Strip any URL-encoded prefix the client might prepend
	payload = strings.TrimPrefix(payload, "/")

	raw, err := base64.RawURLEncoding.DecodeString(payload)
	if err != nil {
		// Try standard base64 as fallback
		raw, err = base64.StdEncoding.DecodeString(payload)
		if err != nil {
			return nil, fmt.Errorf("decode URI payload: %w", err)
		}
	}

	var cfg Config
	if err := json.Unmarshal(raw, &cfg); err != nil {
		return nil, fmt.Errorf("unmarshal config: %w", err)
	}
	return &cfg, nil
}

// SubscriptionMeta holds quota metadata returned by the subscription endpoint.
type SubscriptionMeta struct {
	// SpeedMbps is the downstream speed cap in Mbit/s. 0 = unlimited.
	SpeedMbps int `json:"speed_mbps,omitempty"`
	// TrafficGB is the total traffic quota in GiB. 0 = unlimited.
	TrafficGB int `json:"traffic_gb,omitempty"`
	// UsedGB is how much of the quota has been consumed.
	UsedGB float64 `json:"used_gb,omitempty"`
	// ExpiresAt is the ISO-8601 expiry date-time string.
	ExpiresAt string `json:"expires_at,omitempty"`
	// Status is "active", "expired", or "traffic_exceeded".
	Status string `json:"status,omitempty"`
}

// ParseSubscription fetches a subscription URL, extracts metadata comments,
// and returns the embedded URI along with the parsed metadata.
// Expected format:
//
//	#ktalk-speed-mbps:50
//	#ktalk-traffic-gb:100
//	#ktalk-used-gb:12.5
//	#ktalk-expires-at:2025-12-31T23:59:59Z
//	#ktalk-status:active
//	ktalk://<base64>
func ParseSubscription(body string) (uri string, meta SubscriptionMeta, err error) {
	for _, line := range strings.Split(body, "\n") {
		line = strings.TrimSpace(line)
		switch {
		case strings.HasPrefix(line, "#ktalk-speed-mbps:"):
			fmt.Sscanf(strings.TrimPrefix(line, "#ktalk-speed-mbps:"), "%d", &meta.SpeedMbps)
		case strings.HasPrefix(line, "#ktalk-traffic-gb:"):
			fmt.Sscanf(strings.TrimPrefix(line, "#ktalk-traffic-gb:"), "%d", &meta.TrafficGB)
		case strings.HasPrefix(line, "#ktalk-used-gb:"):
			fmt.Sscanf(strings.TrimPrefix(line, "#ktalk-used-gb:"), "%f", &meta.UsedGB)
		case strings.HasPrefix(line, "#ktalk-expires-at:"):
			meta.ExpiresAt = strings.TrimPrefix(line, "#ktalk-expires-at:")
		case strings.HasPrefix(line, "#ktalk-status:"):
			meta.Status = strings.TrimPrefix(line, "#ktalk-status:")
		case strings.HasPrefix(line, "ktalk://"):
			uri = line
		}
	}
	if uri == "" {
		return "", meta, fmt.Errorf("no ktalk:// URI found in subscription body")
	}
	return uri, meta, nil
}

// FetchSubscription downloads a subscription URL and calls ParseSubscription.
// The actual HTTP call is done by the caller-provided fetch function so that
// the package stays free of network dependencies in tests.
func FetchSubscription(rawURL string, fetch func(string) (string, error)) (*Config, SubscriptionMeta, error) {
	if _, err := url.ParseRequestURI(rawURL); err != nil {
		return nil, SubscriptionMeta{}, fmt.Errorf("invalid subscription URL: %w", err)
	}
	body, err := fetch(rawURL)
	if err != nil {
		return nil, SubscriptionMeta{}, fmt.Errorf("fetch subscription: %w", err)
	}
	uri, meta, err := ParseSubscription(body)
	if err != nil {
		return nil, SubscriptionMeta{}, err
	}
	cfg, err := DecodeURI(uri)
	if err != nil {
		return nil, SubscriptionMeta{}, err
	}
	return cfg, meta, nil
}
